package com.github.lhrb.myshooter;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.github.lhrb.myshooter.Config.Config;
import com.github.lhrb.myshooter.Config.Input;
import org.lwjgl.glfw.*;

import static org.lwjgl.glfw.GLFW.*;

import org.lwjgl.opengl.GL;
import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.system.MemoryUtil.*;

public class Game implements Runnable{
  /* Config start */
  Config myConfig = new Config();
  int width = (Integer) myConfig.getSetting("resolution_width");
  int height = (Integer) myConfig.getSetting("resolution_height");

  static final String gamename = "myShooter";

  private Thread thread;
  private boolean running = false;

  private long window = 0;

  public void start() {
    running = true;
    thread = new Thread(this, gamename);
    thread.start();
  }

  public void init() {
    // Check if glfw starts correctly
    if (!glfwInit()) {
      // we have to handle this
    }
    glfwWindowHint(GLFW_RESIZABLE, GL_TRUE);
    window = glfwCreateWindow(width, height, gamename, NULL, NULL);

    if (window == 0) {
      // we have to handle this
    }

    //get position and center widow
    GLFWVidMode vidmode = glfwGetVideoMode(glfwGetPrimaryMonitor());
    glfwSetWindowPos(window,(vidmode.width() - width) / 2, (vidmode.height() - height) / 2);

    glfwSetKeyCallback(window, new Input());

    glfwMakeContextCurrent(window);
    glfwShowWindow(window);
    GL.createCapabilities();

    glClearColor(1.0f, 1.0f, 1.0f, 1.0f);
    glEnable(GL_DEPTH_TEST);
    System.out.println("OPENGL: "+ glGetString(GL_VERSION));
  }

  public void run() {
    init();
    while (running) {
      update();
      render();

      if(glfwWindowShouldClose(window)) {
        running = false;
      }
    }
  }

  public void update() {
    glfwPollEvents();

    if (Input.keys[GLFW_KEY_SPACE]) {
      System.out.println("blubb");
    }
  }

  public void render() {
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    glfwSwapBuffers(window);
  }

  public static void main(String[] args) {
    new Game().start();
  }
}
